[package]
name = "rustpython"
version = "0.1.0"
authors = ["RustPython Team"]
edition = "2018"
description = "A python interpreter written in rust."
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
exclude = ["wasm/**/*"]

[workspace]
members = [".", "derive", "vm", "wasm/lib", "parser", "compiler", "bytecode"]

[[bench]]
name = "bench"
path = "./benchmarks/bench.rs"


[dependencies]
log="0.4.1"
env_logger="0.5.10"
clap = "2.31.2"
rustpython-compiler = {path = "compiler", version = "0.1.0"}
rustpython-parser = {path = "parser", version = "0.1.0"}
rustpython-vm = {path = "vm", version = "0.1.0"}
rustyline = "4.1.0"
xdg = "2.2.0"

[dev-dependencies.cpython]
version = "0.2"
